### ISSUE TITLE
Приложение крашится в PKPaymentConverter

### ISSUE THREAD

**Issue by ARGAMX** [cloudpayments/CloudPayments_iOSSDKDemo#10]
Приложение крашится в PKPaymentConverter.

В методе
`+(NSString *) convertToString:(PKPayment *)payment {`
нет проверки того, что параметр payment.token.paymentData не nil.

В результате следующий код крашится при попытке создать NSDictionary одно из значений в котором nil.

```
    NSDictionary *paymentDataDictionary = [NSJSONSerialization JSONObjectWithData:payment.token.paymentData options:NSJSONReadingMutableContainers error:nil];
    NSDictionary *cryptogramDictionary = @{@"paymentData": paymentDataDictionary,
                                           @"transactionIdentifier": payment.token.transactionIdentifier,
                                           @"paymentMethod": paymentMethodDictionary
                                           };
```

В процессе разработки и отладки у меня приходил nil в payment.token.paymentData.

Xcode 9.4.1, Swift 4.1, iOS 11.4

**Comment by a-ignatov-cp** [comment]
Эта демка устарела, используйте CloudPayments_iOSCheckout, тот проект так же включает в себя все файлы sdk и полный пример реализации, проведения оплаты.
