### ISSUE TITLE
запуск демо

### ISSUE THREAD

**Issue by StarT3** [cloudpayments/CloudPayments_iOSSDKDemo#2]
В проект добавили ссылки на AFNetworkActivityLogger, а в readme нет упоминания о том как его подключить.
есть только:
git submodule update --init CloudPaymentsAPIDemo/Libraries/AFNetworking/
git submodule update --init CloudPaymentsAPIDemo/Libraries/SVProgressHUD/ 

в итоге -
CloudPayments_iOSSDKDemo/CloudPaymentsAPIDemo/Libraries/AFNetworkingActivityLogger/AFNetworkActivityLogger/AFNetworkActivityLogger.m'

**Comment by acidlynx** [comment]
Спасибо за внимательность!
Документацию скоро обновим.

**Comment by StarT3** [comment]
фиг с ней, с документацией, запустить то как демо?
clang: error: no such file or directory: CloudPayments_iOSSDKDemo/CloudPaymentsAPIDemo/Libraries/AFNetworkingActivityLogger/AFNetworkActivityLogger/AFNetworkActivityLogger.m'
clang: error: no input files

**Comment by StarT3** [comment]
ok, нашел.
https://github.com/AFNetworking/AFNetworkActivityLogger
копируем в директорию в которой xcode их ожидает увидеть.

**Comment by NosovPavel** [comment]
Мда... что-то я сомневаюсь уже на счет того, что решил с cloudpayments работать... до сих по не поправили демо приложение....
