### ISSUE TITLE
Как можно вручную внедрить ваше sdk, чтобы его можно использовать в swift проектах (настройка моста)?

### ISSUE THREAD

**Issue by anatoliykant** [cloudpayments/CloudPayments_iOSSDKDemo#5]

**Comment by ELezov** [comment]
> _No description provided._

[Так попробуй](https://www.youtube.com/watch?v=kdX0HUTFWJo). У меня получилось.

**Comment by a-ignatov-cp** [comment]
https://github.com/cloudpayments/CloudPayments_iOSCheckout - используйте вот этот пример, он на swift, там есть файл моста.
