### ISSUE TITLE
Не компилится в Xcode 10.1 Swift 4.2

### ISSUE THREAD

**Issue by ARGAMX** [cloudpayments/CloudPayments_iOSSDKDemo#8]
Проект не компилится в Xcode 10.1 Swift 4.2.

Добавьте поддержку Swift 4.2.

**Comment by a-ignatov-cp** [comment]
Эта демка устарела, используйте CloudPayments_iOSCheckout, тот проект так же включает в себя все файлы sdk и полный пример реализации, проведения оплаты.
