### ISSUE TITLE
Проект не использует CloudPayments_iOSCheckout

### ISSUE THREAD

**Issue by ARGAMX** [cloudpayments/CloudPayments_iOSSDKDemo#9]
Проект не использует CloudPayments_iOSCheckout, а вместо это несет в себе его классу внутри. Хотя, по инструкции на самом сайте, нужно устанавливать CloudPayments_iOSCheckout. Но эта демка сделана в противоречие с этими указанием.
В результате, когда начинаешь переносить классы из это демки в проект, где установлен CloudPayments_iOSCheckout, начинаются конфликты.

**Comment by a-ignatov-cp** [comment]
Эта демка устарела, используйте CloudPayments_iOSCheckout, тот проект так же включает в себя все файлы sdk и полный пример реализации, проведения оплаты.
